// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('testest1', function() {
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('testest1', async function() {
    await driver.get("http://localhost:3000/add")
    await driver.findElement(By.id("title")).click()
    await driver.findElement(By.id("title")).sendKeys("tasktest")
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("description")).sendKeys("blablabla")
    await driver.findElement(By.css(".btn")).click()
  })
})
